import { createAsyncThunk, createSlice } from "@reduxjs/toolkit";
import { message } from "antd";

const initialState = {
  cart: [],
  tempData: [],
};

export const orderSlice = createSlice({
  name: "order",
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    doAddToCartAction: (state, action) => {
      let cart = state.cart;
      const item = action.payload;
      console.log("item doAddToCartAction", item);
      let isExistIndex = cart.findIndex((c) => c.id === item.id);
      if (isExistIndex === -1) {
        cart.push({
          quantity: item.quantity,
          detail: item.detail,
          id: item.id,
          status: item.status,
        });
      } else {
        cart[isExistIndex].quantity += +item.quantity;
        if (cart[isExistIndex].quantity > item.detail.quantity) {
          cart[isExistIndex].quantity = item.detail.quantity;
        }
      }
      state.cart = cart;
      message.success("Thêm sản phẩm vào giỏ hàng thành công!");
    },
    doUpdateCartAction: (state, action) => {
      let cart = state.cart;
      const item = action.payload;
      let isExistIndex = cart.findIndex((c) => c.id === item.id);
      console.log("item doUpdateCartAction", item);
      if (isExistIndex === -1) {
        console.log("add");
        cart.push({
          quantity: item.quantity,
          detail: item.detail,
          id: item.id,
          status: item.status,
        });
      } else {
        console.log("udpate");
        cart[isExistIndex].quantity = +item.quantity;
        cart[isExistIndex].status = +item.status;
        if (cart[isExistIndex].quantity > cart[isExistIndex].detail.quantity) {
          cart[isExistIndex].quantity = cart[isExistIndex].detail.quantity;
        }
      }
      state.cart = cart;
    },
    clearCart: (state, action) => {
      state.cart = [];
    },
    doDeleteItemCartAction: (state, action) => {
      state.cart = state.cart.filter((c) => c.id !== action.payload);
    },
    doInitalCartWithAccount: (state, action) => {
      state.cart = action.payload;
    },
    doDeleteItemCartAfterDoOrder: (state, action) => {
      state.cart = state.cart.filter((c) => c.status !== 1);
    },
    doInitalTempData: (state, action) => {
      state.tempData = action.payload;
    },
    doClearTempData: (state, action) => {
      state.tempData = [];
    },
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {},
});

export const {
  doAddToCartAction,
  doUpdateCartAction,
  clearCart,
  doDeleteItemCartAction,
  doInitalCartWithAccount,
  doDeleteItemCartAfterDoOrder,
  doInitalTempData,
  doClearTempData,
} = orderSlice.actions;

// The function below is called a selector and allows us to select a value from
// the state. Selectors can also be defined inline where they're used instead of
// in the slice file. For example: `useSelector((state: RootState) => state.counter.value)`
// export const selectCount = (state) => state.counter.value;

// // We can also write thunks by hand, which may contain both sync and async logic.
// // Here's an example of conditionally dispatching actions based on current state.
// export const incrementIfOdd = (amount) => (dispatch, getState) => {
//   const currentValue = selectCount(getState());
//   if (currentValue % 2 === 1) {
//     dispatch(incrementByAmount(amount));
//   }
// };

export default orderSlice.reducer;
